name: Chatbot CI Pipeline
#CI Trigger
on:
  push:
    branches: [ main ]

#Build Process
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    #Frontend Build Preparation
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install


    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    #Backend Dependency Installation
    - name: Install Backend Dependencies
      run: |
        cd backend
        pip install flask python-dotenv requests